import q1_1, q1_2, q2, q3, q4, q5_1, q5_2, q5_3, q6, q7

print('Executing solution for Q1.1')
q1_1.main()
print('--------------------------------------------------------------')
print('Executing solution for Q1.2')
q1_2.main()
print('--------------------------------------------------------------')
print('Executing solution for Q2')
q2.main()
print('--------------------------------------------------------------')
print('Executing solution for Q3')
q3.main()
print('--------------------------------------------------------------')
print('Executing solution for Q4')
q4.main()
print('--------------------------------------------------------------')
print('Executing solution for Q5.1')
q5_1.main()
print('--------------------------------------------------------------')
print('Executing solution for Q5.2')
q5_2.main()
print('--------------------------------------------------------------')
print('Executing solution for Q5.3')
q5_3.main()
print('--------------------------------------------------------------')
print('Executing solution for Q6')
q6.main()
print('--------------------------------------------------------------')
print('Executing solution for Q7')
q7.main()